### ISSUE TITLE
problem with font inside app

### ISSUE THREAD

**Issue by T0MZUK** [CodeDead/opal#130]
I have problem with font in Windows 11 - its almost unreadable
![_____](https://github.com/user-attachments/assets/b8f90c75-f33e-497f-b4d8-0c8639d32f41)

**Comment by CodeDead** [comment]
Hello,

Did you tinker with your system fonts on Windows 11 or with Java fonts in any way?
The default setting for Opal is that it will use the default font that is available on the system.

Kind regards

Alessandro Mercier

**Comment by T0MZUK** [comment]
I am an illustrator and I have a lot of fonts installed, but I haven't
changed anything in Windows itself. But I found what is the source of the
problem. This is application StartAllBack - the settings of this
application are causing the problem. So the problem is solved, sorry for
bothering you.

tbest regards
ToMK


*.-----------.                       .------------.*
*| Tomasz Żuk \ ***@***.*** ***@***.***> / 501-176-795
|'----------o  `-------------------'   o----------'*



czw., 3 paź 2024 o 15:09 CodeDead ***@***.***> napisał(a):
