### ISSUE TITLE
Question about Audience "Football"

### ISSUE THREAD

**Issue by uDEV2019** [CodeDead/opal#42]
Football sound to me more like amercian football as football (soccer).
Maybe you change the icon of if i'm right with my assessment

**Comment by CodeDead** [comment]
That is true, I am open for icon changes or translation changes but it's kind of an issue that will depend on where you live in the world and will probably be an issue for a very long while considering human nature.

**Comment by uDEV2019** [comment]
The Cheerleaders that are yelling are more known for american football as for soccer or other sports.
In the end it really depends on where you live.

**Comment by CodeDead** [comment]
I'll leave this open and see if others feel the same way. In the end I think the only reasonable way to get to a conclusion would be to let the community vote on the matter. The change really isn't difficult to implement so we'll probably best wait and see what comes out of it!

**Comment by CodeDead** [comment]
Hi @uDEV2019 

I've decided to rename the current key to 'Rugby football' and will change the icon to better reflect the term.
You can find the latest translations in the `development` branch:
https://github.com/CodeDead/opal/tree/development

Or in the appropriate PR #45  for this change:
https://github.com/CodeDead/opal/pull/45

With this change, I will close this issue and probably add a Football audience sound too in a future update.
